Adicionada JDBCTable
crazynds/FyiDatabase-Java pull request #1
Opened 2023-11-08 15:27 UTC by matheus-delazeri

Permite a instanciação de tables suportadas pelo JDBC (MySQL, PostgreSQL, Oracle, etc).

2023-11-08 15:29 UTC, matheus-delazeri commented on src/main/java/sgbd/source/Source.java
> -        translatorApi = header.getPrototype().validateColumns();
Aqui permite criar a source sem um Prototype definido no header pois no caso das JDBC tables o Prototype é criado automaticamente no open()

2023-11-08 16:48 UTC, crazynds requested changes
Algumas mudanças pequenas

2023-11-08 16:48 UTC, crazynds commented on pom.xml
> +      <artifactId>postgresql</artifactId>
Testar postgresql.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +    }
Se o JDBC table precisa ter ['connection-url', 'connection-user', 'connection-password'], adicionar um if checando se a informação existe no header, se não tiver dar um throw no DatabaseException com informações sobre oq ta faltando.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +        if (connectionUrl != null) {
Remover esse if, pq se foi checado no controller se tava tudo certo, então os if's de null não precisam existir.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +        } catch (Exception e) {
Se a exception for um DatabaseException, emitir para fora dessa função.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +                e.printStackTrace();
Se der um SqlException, criar um DatabaseException com as mensagens do SqlException. Isso é importante para travar o programa se der algum erro. E depois a ferramenta tratar o erro.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +        } catch (SQLException e) {
Try catch silencioso. Não precisa printar mensagem, nem emitir databaseException.

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/JDBCTable.java
> +            e.printStackTrace();
throw new DatabaseException(...)

2023-11-08 16:48 UTC, crazynds commented on src/main/java/sgbd/source/table/OracleTable.java
> +            e.printStackTrace();
throw new DatabaseException(...)

2023-11-08 23:27 UTC, matheus-delazeri reviewed
Pendências resolvidas

2023-11-09 02:42 UTC, crazynds approved these changes

2023-11-09 02:42 UTC, merged